const COLOR_LABEL = 'Choose a color';
const SIZE_LABEL = 'Choose a size';
const CART_BTN = 'Add to Cart';
const QUANTITY_LABEL = 'Choose a Quantity';
const PRODUCT_INFO_LABEL = 'PRODUCT INFO';
const RETURN_REFUND_POLICY = 'RETURN AND REFUND POLICY ';
const SHIPPING_INFO = 'SHIPPING INFO';

export {
  COLOR_LABEL,
  SIZE_LABEL,
  CART_BTN,
  QUANTITY_LABEL,
  PRODUCT_INFO_LABEL,
  RETURN_REFUND_POLICY,
  SHIPPING_INFO,
};
